name: test

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt-get install flex libfl-dev

      - name: Build and test
        run: make
