name: test

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt-get install flex libfl-dev

      - name: Build
        run: |
          bison -d parser.y -o parser.c
          flex -o lexer.c lexer.l
          gcc lexer.c parser.c -lfl -o simplecalc

      - name: Test
        run: ./run_tests.sh
